'\" t
.\"     Title: command
.\"    Author: j5pu
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2021-12-26
.\"    Manual: Bats.sh Manual
.\"    Source: Bats.sh 0.2.7
.\"  Language: English
.\"
.TH "BATS.SH" "7" "2021-12-26" "Bats.sh 0.2.7" "Bats.sh Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
bats.sh \- add & updates bats libraries, sources libraries, set helper variables and run bats tests
.SH "SYNOPSIS"
.sp
\fBbats.sh\fP [\fIINFO ARGUMENT\fP] [\fICOMMON OPTION\fP] [\fIOPTIONAL ARGUMENT\fP] \fIARGUMENT\fP...
.SH "AUTHOR"
.sp
j5pu