tap "caarlos0/tap"
brew "asciidoctor"
brew "twine-pypi"
brew "caarlos0/tap/svu"

tap "homebrew/bundle"
tap "homebrew/core"
if RUBY_PLATFORM[/darwin/]
  tap "caarlos0/tap"
  tap "homebrew/cask"
  tap "homebrew/cask-fonts"
  tap "homebrew/cask-versions"
  tap "homebrew/services"
  tap "j5pu/bats-libs"
  tap "mas-cli/tap"
  brew "asciidoctor"
  brew "makeself"
  brew "mas"
  brew "most"
  brew "twine-pypi"
  brew "caarlos0/tap/svu"
  brew "j5pu/bats-libs/bats-libs"
end
