name: remove

on:
  workflow_dispatch:

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - uses: j5pu/actions/pypirm@main
        with:
          pypi_password: ${{ secrets.PYPI_CLEANUP_PASSWORD }}
